version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    target_branch: "development"
    update_schedule: "live"
    default_assignees:
      - jwu910
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
